package loopsandarrays.homework.car;

/**
 * Created by Admin on 11.10.16.
 */
public enum CarType {
    MICROCAR, SUBCOMPACT_CAR, ECONOMY_CAR, OMPACT_CAR, ID_SIZE_CAR, ENTRY_LEVEL_LUXURY_CAR, FULL_SIZE_CAR, MID_SIZE_LUXURY_CAR, FULL_SIZE_LUXURY_CAR, GRAND_TOURER, SUPERCAR, CONVERTIBLE, ROADSTER, MPV, MINIVAN, CARGO_VAN, PASSENGER_VAN, MINI_SUV, COMPACT_SUV, MID_SIZE_SUV, FULL_SIZE_SUV, MINI_PICKUP_TRUCK, MID_SIZE_PICKUP_TRUCK, FULL_SIZE_PICKUP_TRUCK, HEAVY_DUTY_PICKUP_TRUCK, SPECIAL_PURPOSE_VEHICLE;
}
