/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2016-11-08 00:48:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/tags/page/header.tag", Long.valueOf(1478566073859L));
    _jspx_dependants.put("/WEB-INF/tags/page/carousel.tag", Long.valueOf(1478408022937L));
    _jspx_dependants.put("/WEB-INF/tags/page/css.tag", Long.valueOf(1478408022906L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1478197958000L));
    _jspx_dependants.put("/WEB-INF/tags/page/js.tag", Long.valueOf(1478408022734L));
    _jspx_dependants.put("jar:file:/D:/ariezz/SoftServe_java/testservlet/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/tags/page/footer.tag", Long.valueOf(1478432062703L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <title>The best ever company</title>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_page_005fcss_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_page_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <p style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      if (_jspx_meth_page_005fcarousel_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque dolores facilis odio, optio quaerat repellendus rerum tenetur totam voluptatibus? Excepturi laboriosam praesentium quod? Beatae esse ipsam saepe sint! Facere?</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      if (_jspx_meth_page_005ffooter_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_page_005fjs_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_page_005fcss_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:css
    org.apache.jsp.tag.web.page.css_tag _jspx_th_page_005fcss_005f0 = (new org.apache.jsp.tag.web.page.css_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_page_005fcss_005f0);
    _jspx_th_page_005fcss_005f0.setJspContext(_jspx_page_context);
    _jspx_th_page_005fcss_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_page_005fcss_005f0);
    return false;
  }

  private boolean _jspx_meth_page_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:header
    org.apache.jsp.tag.web.page.header_tag _jspx_th_page_005fheader_005f0 = (new org.apache.jsp.tag.web.page.header_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_page_005fheader_005f0);
    _jspx_th_page_005fheader_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/jsps/main.jsp(27,0) name = department type = java.util.ArrayList<com.ariezz.model.Department> reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_page_005fheader_005f0.setDepartment((java.util.ArrayList) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data}", java.util.ArrayList.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    _jspx_th_page_005fheader_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_page_005fheader_005f0);
    return false;
  }

  private boolean _jspx_meth_page_005fcarousel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:carousel
    org.apache.jsp.tag.web.page.carousel_tag _jspx_th_page_005fcarousel_005f0 = (new org.apache.jsp.tag.web.page.carousel_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_page_005fcarousel_005f0);
    _jspx_th_page_005fcarousel_005f0.setJspContext(_jspx_page_context);
    _jspx_th_page_005fcarousel_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_page_005fcarousel_005f0);
    return false;
  }

  private boolean _jspx_meth_page_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:footer
    org.apache.jsp.tag.web.page.footer_tag _jspx_th_page_005ffooter_005f0 = (new org.apache.jsp.tag.web.page.footer_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_page_005ffooter_005f0);
    _jspx_th_page_005ffooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_page_005ffooter_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_page_005ffooter_005f0);
    return false;
  }

  private boolean _jspx_meth_page_005fjs_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:js
    org.apache.jsp.tag.web.page.js_tag _jspx_th_page_005fjs_005f0 = (new org.apache.jsp.tag.web.page.js_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_page_005fjs_005f0);
    _jspx_th_page_005fjs_005f0.setJspContext(_jspx_page_context);
    _jspx_th_page_005fjs_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_page_005fjs_005f0);
    return false;
  }
}
