package conditional.homework.dog;


public enum Breed {
    UNKNOWN, GERMAN_SHEPHERD, POODLE, CHIHUAHUA, GOLDEN_RETRIEVER, YORKSHIRE_TERRIER, DACHSHUND, BEAGLE, BOXER, MINIATURE_SCHNAUZER, SHIH_TZU, BULLDOG, GERMAN_SPITZ, ENGLISH_COCKER_SPANIEL, CAVALIER_KING_CHARLES_SPANIEL, FRENCH_BULLDOG, PUG, ROTTWEILER, ENGLISH_SETTER, MALTESE, ENGLISH_SPRINGER_SPANIEL, GERMAN_SHORTHAIRED_POINTER, STAFFORDSHIRE_BULL_TERRIER, BORDER_COLLIE, SHETLAND_SHEEPDOG, DOBERMANN, WEST_HIGHLAND_WHITE_TERRIER, BERNESE_MOUNTAIN_DOG, GREAT_DANE, BRITTANY_SPANIEL;
}
